version: 2.1

jobs:
  # In this example, we are not actually building and pushing docker image
  build-and-upload-image:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Build and push docker image
          command: |
            mkdir tmp
            echo "Building docker image..."
            echo "Push docker image..."
            echo "232490755822.dkr.ecr.us-west-2.amazonaws.com/awesome-release/react-express-mongodb/backend:main" > tmp/backend_image.txt
            echo "232490755822.dkr.ecr.us-west-2.amazonaws.com/awesome-release/react-express-mongodb/frontend:main" > tmp/frontend_image.txt
      - persist_to_workspace:
          root: .
          paths:
            - tmp/*

  create-release-environment:
    docker:
      - image: public.ecr.aws/b4g8c3s2/release-cli:v0.3.0-beta2
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Create a new Release environment
          command: |
            BRANCH=e2e-testing
            FRONTEND_IMAGE=$(cat tmp/frontend_image.txt)
            BACKEND_IMAGE=$(cat tmp/backend_image.txt)
            FRONTEND=frontend
            BACKEND=backend
            release environments create \
              --account "$RELEASE_ACCOUNT_ID" \
              --app "$RELEASE_APP_ID" \
              --branch "$BRANCH" \
              --image-overrides "$FRONTEND=$FRONTEND_IMAGE" \
              --image-overrides "$BACKEND=$BACKEND_IMAGE" \
              --output json \
              --wait > tmp/res.json
      - persist_to_workspace:
          root: .
          paths:
            - tmp/*

  run-e2e-tests:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Create Release Environment
          command: |
            echo "Install dependencies and run E2E tests..."
            FRONTEND_URL=$(jq -r '.environment.hostnames | .[] | select(.target=="frontend").hostname' res.json)
            BACKEND_URL=$(jq -r '.environment.hostnames | .[] | select(.target=="backend").hostname' res.json)
            jq -n --arg baseUrl "https://$FRONTEND_URL" '{ baseUrl: $baseUrl }' > cypress.json
            jq -n --arg backendUrl "https://$BACKEND_URL" '{ backendUrl: $backendUrl }' > cypress.env.json
            sudo apt-get update
            sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
            npm install
            npm run cy:run

workflows:
  my_workflow:
    jobs:
      - build-and-upload-image
      - create-release-environment:
          requires: [build-and-upload-image]
      - run-e2e-tests:
          requires: [create-release-environment]