name: GitHub Actions Demo

on: [push]

jobs:
  build-and-upload-image:
    runs-on: ubuntu-latest
    steps:
      - id: steps1
        run: |
            echo "Building docker image..."
            echo "Push docker image..."
            mkdir -p /tmp
            echo "::set-output name=image::232490755822.dkr.ecr.us-west-2.amazonaws.com/awesome-release/react-express-mongodb/backend:main"
    outputs:
      image: ${{ steps.step1.outputs.image }}
  create-release-environment:
    needs: [build-and-upload-image]
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/b4g8c3s2/release-cli
    steps:
      - run: echo ${{needs.build-and-upload-image.outputs.image}}

