name: GitHub Actions Demo

on: [push]

jobs:
  build-and-upload-image:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
  create-release-environment:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/b4g8c3s2/release-cli
    steps:
      - run: echo ${{needs.build-and-upload-image.outputs.output1}} ${{needs.build-and-upload-image.outputs.output2}}



