name: GitHub Actions Demo
on: [push]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "building docker image..."
          echo "uploading docker image..."
          echo "232490755822.dkr.ecr.us-west-2.amazonaws.com/awesome-release/react-express-mongodb/backend:main" > image_name
      - name: upload image name
        uses: actions/upload-artifact@v3
        with:
          name: image_name
          path: image_name
  create_release_environment:
    name: create release environment
    needs: build_and_upload
    runs-on: ubuntu-latest
    container: public.ecr.aws/b4g8c3s2/release-cli
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: image_name
      - shell: bash
        run: |
          IMAGE_URL=$(cat image_name)
          BRANCH=e2e-testing
          SERVICE=backend
          /release environments create \
            --account "$RELEASE_ACCOUNT_ID" \
            --app "$RELEASE_APP_ID" \
            --branch "$BRANCH" \
            --image-overrides "$SERVICE=$IMAGE_URL" \
            --output json \
            --wait > tmp/json

